AWSTemplateFormatVersion: '2010-09-09'
Description: PhotoS3
Parameters:
  BucketPrefix:
    Type: String
    Description: Prefix for S3 bucket name
    ConstraintDescription: must be valid S3 bucket characters and prefix+accountnumber+suffix <=63 characters
    Default: photos3-
    MinLength: 0
    MaxLength: 63
    AllowedPattern: '[-_\.a-zA-Z0-9]*'

  BucketSuffix:
    Type: String
    Description: Suffix for S3 bucket name
    ConstraintDescription: must be valid S3 bucket characters and prefix+accountnumber+suffix <=63 characters
    Default: ''
    MinLength: 0
    MaxLength: 63
    AllowedPattern: '[-_\.a-zA-Z0-9]*'

  S3DeployKey:
    Type: String
    Description: Code revision
    ConstraintDescription: must be a valid S3 key
    MinLength: 1
    AllowedPattern: '^[a-f0-9]+$'

  NewImageCheckSchedule:
    Type: String
    Description: CloudWatch Event schedule expression for processing new images
    ConstraintDescription: must be a valid rate
    Default: 'rate(5 minutes)'
    AllowedPattern: '^rate\(.*\)$'

Conditions: {}
Mappings: {}

Outputs:
  UploadBucket:
    Description: S3 bucket for uploads
    Value: !Ref PhotoBucket

  MetadataTable:
    Description: DynamoDB table for image metadata
    Value: !Ref PhotoMetaTable

Resources:
  PhotoBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${BucketPrefix}${AWS::AccountId}${BucketSuffix}
      LifecycleConfiguration:
        Rules:
          - AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 1
            ExpirationInDays: 14
            NoncurrentVersionExpirationInDays: 14
            Prefix: code/
            Status: Enabled
          - AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 1
            NoncurrentVersionExpirationInDays: 1
            Prefix: source/
            Status: Enabled
          - AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 1
            NoncurrentVersionExpirationInDays: 1
            Prefix: thumbnails/
            Status: Enabled

      NotificationConfiguration:
        QueueConfigurations:
          - Event: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: source
            Queue: !Sub ${NewImageQueue.Arn}
      Tags:
        - Key: Platform
          Value: PhotoS3
        - Key: Purpose
          Value: Storage

  NewImageQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 300

  NewImageQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref NewImageQueue
      PolicyDocument:
        Version: 2012-10-17
        Id: S3Publish
        Statement:
          - Sid: S3PublishMessage
            Effect: Allow
            Principal: {Service: s3.amazonaws.com}
            Action: ['SQS:SendMessage']
            Resource: !Sub ${NewImageQueue.Arn}
            Condition:
              ArnLike:
                'aws:SourceArn': !Sub ${PhotoBucket.Arn}

  NewImageWorkerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: ['sts:AssumeRole']
      Path: /
      Policies:
        - PolicyName: sqsrx
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - 'sqs:DeleteMessage*'
                  - 'sqs:GetQueueAttributes'
                  - 'sqs:GetQueueUrl'
                  - 'sqs:ListDeadLetterSourceQueues'
                  - 'sqs:ReceiveMessage'
                Resource: !Sub ${NewImageQueue.Arn}

              - Effect: Allow
                Action: 'sqs:ListQueues'
                Resource: !Sub 'arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:*'

        - PolicyName: logs
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - logs:*
                Resource: arn:aws:logs:*:*:*

        - PolicyName: s3fetch
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - 's3:ListBucket*'
                Resource: !Sub ${PhotoBucket.Arn}

              - Effect: Allow
                Action:
                  - 's3:GetObject*'
                Resource: !Sub ${PhotoBucket.Arn}/*

        - PolicyName: dynamodb
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - 'dynamodb:Batch*'
                  - 'dynamodb:DeleteItem'
                  - 'dynamodb:DescribeTable'
                  - 'dynamodb:GetItem'
                  - 'dynamodb:PutItem'
                  - 'dynamodb:Query'
                  - 'dynamodb:Scan'
                  - 'dynamodb:UpdateTable'
                Resource: !Sub ${PhotoMetaTable.Arn}

  PhotoMetaTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: S3Key
          AttributeType: S
      KeySchema:
        - KeyType: HASH
          AttributeName: S3Key
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      Tags:
        - Key: Platform
          Value: PhotoS3
        - Key: Purpose
          Value: Metadata

  NewImageWorker:
    Type: AWS::Lambda::Function
    Properties:
      Description: Initially processes new images
      Handler: photos3.lambda.process_new_image_queue
      Code:
        S3Bucket: !Ref PhotoBucket
        S3Key: !Sub code/${S3DeployKey}.zip
      MemorySize: 256
      Role: !Sub ${NewImageWorkerRole.Arn}
      Runtime: python3.6
      Timeout: 300
      Environment:
        Variables:
          TASK_QUEUE: !Sub ${NewImageQueue.QueueName}
          META_TABLE: !Sub ${PhotoMetaTable}
      Tags:
        - Key: Platform
          Value: PhotoS3
        - Key: Purpose
          Value: ImageProcessing

  NewImageRule:
    Type: AWS::Events::Rule
    Properties:
      Description: Check for new images
      ScheduleExpression: !Sub ${NewImageCheckSchedule}
      State: ENABLED
      Targets:
        - Arn: !Sub ${NewImageWorker.Arn}
          Id: NewImageWorker

  NewImageRulePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Sub ${NewImageWorker}
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !Sub ${NewImageRule.Arn}

# vim: ts=2:sw=2
